local constants = require("constants")

-- require("prototypes/items")
-- require("prototypes/fluids")
-- require("prototypes/recipecategories")
-- require("prototypes/recipes")
-- require("prototypes/entities")

require("prototypes.treesys.items")
require("prototypes.treesys.fluids")
require("prototypes.treesys.recipecategories")
require("prototypes.treesys.recipes")
require("prototypes.treesys.entities")
-- require("prototypes.treesys.sound")

require("prototypes.weaponsys.items")
-- require("prototypes.weaponsys.fluids")
-- require("prototypes.weaponsys.recipecategories")
require("prototypes.weaponsys.recipes")
require("prototypes.weaponsys.entities")
require("prototypes.weaponsys.sound")

-- require("prototypes.ingotsys.items")
-- require("prototypes.ingotsys.fluids")
-- require("prototypes.ingotsys.recipecategories")
require("prototypes.ingotsys.recipes")
-- require("prototypes.ingotsys.entities")
-- require("prototypes.ingotsys.sound")

-- require("prototypes.fogbanksys.items")
-- require("prototypes.fogbanksys.fluids")
-- require("prototypes.fogbanksys.recipecategories")
require("prototypes.fogbanksys.recipes")
-- require("prototypes.fogbanksys.entities")
-- require("prototypes.fogbanksys.sound")

-- require("prototypes.soundsys.items")
-- require("prototypes.soundsys.fluids")
-- require("prototypes.soundsys.recipecategories")
-- require("prototypes.soundsys.recipes")
-- require("prototypes.soundsys.entities")
require("prototypes.soundsys.sound")

require("prototypes.tanksys.items")
-- require("prototypes.tanksys.fluids")
-- require("prototypes.tanksys.recipecategories")
require("prototypes.tanksys.recipes")
require("prototypes.tanksys.entities")
-- require("prototypes.tanksys.sound")
require("prototypes.tanksys.technology")